language:
  - python
  - node_js

node_js:
  - "0.10"


python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - npm install
  - pip install -r requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests
  - python setup.py install
  - git config --global user.name Enbee Diff
  - git config --global user.email example@example.com
  - make test-diff
  - make test-merge
  - flake8 nbdiff
  - flake8 tests
  - grunt

notifications:
  email:
    - "bsplay@gmail.com"
